version: '2'

services:
    php:
        build: ./php
        restart: always
        volumes:
            - ../app:/var/www/app
        container_name: 'php'
    nginx:
        image: nginx:latest
        restart: always
        ports:
            -   "5555:80"
        volumes:
            -   ../app:/var/www/app
            -   ../nginx/main.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   php
    mysql:
        image: mysql:5.5
        restart: always
        ports:
            -   "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel8
            MYSQL_PASSWORD: root
        container_name: 'mysql'
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
    node:
        image: node:14.12.0
        container_name: node
        restart: unless-stopped
        tty: true
        volumes:
            - ../app:/var/www/app
        ports:
            - "5137:5137"